### ISSUE TITLE
OSX Icons

### ISSUE THREAD

**Issue by Mc128k** [pydio/pydio-sync#103]
Hi
Thanks for making Pydio open source.
I would like to report just as a small cosmetic improvement, icons in OS X should match the UI a bit more. Specifically the toolbar icon (should be B/W not coloured by default) and the Pydio special folder in the user directory (match Yosemite's new look, retain the existing one for older OS). Also the top icon sometimes disappears, but it happens rarely.

Thanks

**Comment by 7omate** [comment]
Wrong repo.

See https://github.com/pydio/pydio-sync-ui
