### ISSUE TITLE
Subdirectory (cannot be 3+ deep)

### ISSUE THREAD

**Issue by rubenverhoef** [pydio/pydio-sync#109]
I want to sync only one folder of my workspace:
WORKSPACE -> DIR1-> DIR2-> DIR3

But i only can select DIR2 as subdirectory, i cannot select a "deeper" subdirectory.

I use pydiosync 1.0.2 (windows) and pydio-core 6.2.0 (freebsd)

Please add this :)

EDIT:
info about version

**Comment by 7omate** [comment]
This isn't really a priority... You could manually edit your configs.json to synchronize only what suits you
