### ISSUE TITLE
Hard to select last workspace in the list of workspaces

### ISSUE THREAD

**Issue by tmlmt** [pydio/pydio-sync#113]
In "Edit Sync", when I drop down the menu to select the workspace I want, the last item of the menu gets under the footer which contains the back arrow, "Delete sync" and "Save parameters". I managed to select it anyway, because a couple of pixels of that item stays above, but it is quite impractical. Would it be possible to fix this ?

**Comment by 7omate** [comment]
It should be fixed now.
