### ISSUE TITLE
Folder doesn't sync

### ISSUE THREAD

**Issue by tmlmt** [pydio/pydio-sync#114]
I added a SYNC on a specific workspace (this workspace is a workspace shared by another Pydio user to me), which contains one xlsx file. PydioSync says the folder is synchronized but it is not. There is nothing in my local folder, whereas the workspace on the server is populated. 

When I disable and re-enable the SYNC, it says "1 change detected" but nothing happens. Same when I quit and launch PydioSync again.

Running PydioSync v1.0.3 on Windows 7 Pro SP1 64bits; server running Pydio 6.2.1

**Comment by sagaru** [comment]
Hello,
If you have questions, consider posting it on our dedicated forum meant for these, once it is qualified as a bug, you can post here.
https://pydio.com/en/community
