### ISSUE TITLE
Preferences window not displayed directly

### ISSUE THREAD

**Issue by Kwadz** [pydio/pydio-sync#122]
Hello,

I am on OSX Yosemite, I use PydioSync v1.0.3. When I select "Preferences" in PydioSync from the top menu bar of OSX, the window isn't opened. After verification, in fact the window is opened but not focused, it's behind other windows. I had to use Mission Control to realize this.

Does someone have the same behaviour?

**Comment by 7omate** [comment]
Isn't this happening only when the window is already opened?

**Comment by Kwadz** [comment]
The problem happens when the window is closed. The behavior is normal when the window is already opened (if I put another window on focus, the preference menu set the PydioSync window on focus well).

**Comment by 7omate** [comment]
I only notice this behavior when another window is full screen. Could you check with the latest version?

**Comment by Kwadz** [comment]
Same problem with the latest version (1.2.1). As you said if the current window is in full screen (or simply maximized) it hides the Pydio window because the latter is not on the focus and should be.

**Comment by 7omate** [comment]
Status?

**Comment by Kwadz** [comment]
I installed v1.2.5, now it's ok.
