### ISSUE TITLE
~$ Microsoft Office temp files pattern

### ISSUE THREAD

**Issue by PatrickChen** [pydio/pydio-sync#123]
Opening modern Micorosoft Office files (.docx, .pptx, etc) generates hidden temporary files in the format ~$filename.docx, ~$filename.pptx, etc. 
If a PydioSync Synchronization is monitoring a folder when an Office file is opened, it syncs these temporary files up to the server. Usually it is acceptable because when the Office program is closed and the ~$filename.docx file is automatically deleted, PydioSync reads that as a Delete and will send the copy on the server to the account’s Recycle Bin.
Unfortunately, somewhat frequently, if the user closes the Office program at the wrong time, when the ~$filename.docx file has been recently synced, the file gets “stuck” in the cloud and get synced back to the user’s workstation as a real/permanent file. From there, the user can try deleting it from the File Explorer, but there’s a 50/50 chance it’ll be deleted from the server or it will stay stuck and get synced down to their workstation again.

---
I personally resolved this issue by adding an exclusion pattern through the PydioSync 1.0.4 GUI, later by adding it directly to the configs.json and restarting Pydio. The exclusion pattern I used was "~$*", which worked for the Office hidden temp files, but I did not do extensive testing to see if it negatively affected other files. 
Per Charles (https://pydio.com/forum/f/topic/microsoft-office-temp-files-getting-stuck/#post-98717), a default exclusion pattern for the ~$ hidden temp files might be good to add to the PydioSync client.

**Comment by sagaru** [comment]
@PatrickChen Thanks for your suggestion, we consider your comments, we'll inclide this to exclude pattern list soon.

**Comment by sagaru** [comment]
Temp files included in default excludes pattern list. https://github.com/pydio/pydio-sync/commit/ae5c53656de7517f48a1c844a68735f58582d38c
