### ISSUE TITLE
IOError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by yavama** [pydio/pydio-sync#125]
i got this when runing python -m pydio.main
what's wrong ? 

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/pydio-0.1-py2.7.egg/pydio/main.py", line 105, in <module>
    global_config_manager.set_general_config(global_config_manager.default_settings)
  File "/usr/local/lib/python2.7/dist-packages/pydio-0.1-py2.7.egg/pydio/utils/global_config.py", line 214, in set_general_config
    with open(global_config_file, 'w') as conf_file:
IOError: [Errno 2] No such file or directory: '/home/dhouha/.local/share/Pydio/general_config.json'

**Comment by 7omate** [comment]
> /home/dhouha/.local/share/Pydio/general_config.json

Doesn't exist, you need a *configs.json*.

I guess, the easiest way to get one would be get one would be to run from the binary we have on https://pydio.com/en/products/downloads/pydiosync-desktop-app which is easier to interact with... (Except on linux for now...)

**Comment by yavama** [comment]
in fact i'm looking for a sync client without GUI 
is pydio-sync what i'm looking for ??

**Comment by sagaru** [comment]
@yavama Yes, once you download the binaries for Linux, you can simply run the pydio-agent. which is nothing but sync client without GUI.

**Comment by yavama** [comment]
@sagaru how to run it plz?

**Comment by sagaru** [comment]
@yavama just run the binary pydio-agent as `./pydio-agent`  [Download pydio-sync](https://download.pydio.com/pub/pydio-sync/release/1.0.4/PydioSync-Linux-1.0.4.tar.gz)

**Comment by sagaru** [comment]
@yavama I willbe closing this issue, as mentioned in [Readme](https://github.com/pydio/pydio-sync#reporting-issues), If you have any questions, please consider finding or posting them on our [dedicated forum](https://pydio.com/en/community) under "PydioSync Issues", once it is qualified as a bug, you can post them here.

**Comment by yavama** [comment]
thanks for help :)
