### ISSUE TITLE
cannot execute binary file

### ISSUE THREAD

**Issue by yavama** [pydio/pydio-sync#126]
that's what i got when runing  ./pydio-agent
bash: ./pydio-agent: cannot execute binary file

**Comment by sagaru** [comment]
@yavama On which OS are you running this?

**Comment by yavama** [comment]
ubuntu 14.04 
but my machine is 32bits i think

**Comment by 7omate** [comment]
`uname -a`
or maybe `chmod +x pydio-agent`

**Comment by sagaru** [comment]
@yavama we don't have binaries for ubuntu 32 bit machines for the moment, you should run it from source.

**Comment by yavama** [comment]
i've tried with ubuntu 64 bit machine and now i have this 

what username and password ??
![screenshot from 2016-02-25 19 54 58](https://cloud.githubusercontent.com/assets/17200559/13330746/8b328ee6-dbfa-11e5-80ce-bafcbcec8563.png)

**Comment by 7omate** [comment]
https://pydio.com/forum/f/topic/remote-access-of-headless-pydio-ui/

**Comment by yavama** [comment]
this link doesn't help me :/ how to solve this ! 
i dont know the user name and the password

**Comment by sagaru** [comment]
@yavama as we informed you before and as in [Readme](https://github.com/pydio/pydio-sync#reporting-issues), If you have any questions, consider finding or posting them on our [dedicated forum](https://pydio.com/en/community) under "PydioSync Issues", once it is qualified as a bug, you can post them here.

**Comment by 7omate** [comment]
`pydio-agent --api_user=yavama --api_password=yavama` 

Then login with *yavama* and *yavama*

https://pydio.com/forum/f/topic/remote-access-of-headless-pydio-ui/#post-96951
