### ISSUE TITLE
Conflict Resolution doesn't work

### ISSUE THREAD

**Issue by cHolzberger** [pydio/pydio-sync#129]
When i try to solve my conflicts the conflicts will be there again with the next sync. My current solution is to rename the file locally, let it fetch the remote file, delete it and rename my local file.

Latest stable PydioSync and Pydio. 

- can't find anything related in the logs

**Comment by 7omate** [comment]
Is it concerning empty files?

**Comment by sagaru** [comment]
@cHolzberger I guess the issue you're pointing to have been fixed already in  acc936157344d6119aa5c5fa369aab31b31ddadb & 8028037ad14425c353e62b1acee03a9f8cc3333f

The commit is after the last stable release, you can test the dev build from https://download.pydio.com/pub/pydio-sync/develop/packages/

I'm closing this issue for now, feel free to reopen if you still have same issue.
