### ISSUE TITLE
PydioSync 1.2.0 install version number wrong

### ISSUE THREAD

**Issue by PatrickChen** [pydio/pydio-sync#130]
Minor issue
At least on Windows32 install, PydioSync 1.2.0 recently released does not have an updated version number, so it attempts to install as PydioSync 1.0.4, causing Windows Installer to error with 
> "Another vesrion of this product is already installed. Installation of this version cannot continue. To configure or remove the existing version of this product, use Add/Remove Programs on the Control Panel."

Workaround was to Uninstall existing 1.0.4 PydioSync, marking retain settings, then install PydioSync 1.2.0
After installing 1.2.0, checking the Add/Remove Programs shows its registered version number is 1.0.4

**Comment by sagaru** [comment]
@PatrickChen Thanks for reporting, I confirm the issue. It has been fixed, you'll be able to see the correct version number in the next dev release.
