### ISSUE TITLE
libffi-dev needed for Installation on Ubuntu 14.04.

### ISSUE THREAD

**Issue by neumann89** [pydio/pydio-sync#133]
No package 'libffi' found

running install
...
c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory

 #include <ffi.h>

**Comment by sagaru** [comment]
The latest stable versions are not yet compatible with ubuntu, consider using [PydioSync v1.0.3](https://download.pydio.com/pub/pydio-sync/release/1.0.3/) for the moment.

**Comment by 7omate** [comment]
It should be working now.

**Comment by dagmarkrefting** [comment]
please add "sudo apt-get install libffi-dev" to the README installation instructions. I had the same problem.
