### ISSUE TITLE
problem sync other users accounts

### ISSUE THREAD

**Issue by riazz** [pydio/pydio-sync#137]
Hello, i have just installed pydio-sync on my Ubuntu machine 

it works well with "python main.py --api_user=admin-login --api_password=admin-password"

when i want to sync simple user account with "python main.py --api_user=user-login --api_password=user-login" 
nothing changes it keep syncing the admin account 

how to make it sync other users accounts plz ? what should i change ?

**Comment by 7omate** [comment]
I don't understand your problem, *--api_* sets the credentials to access the web interface locally. Visit http://localhost:5556/ to access it and configure sync tasks.
