### ISSUE TITLE
suggestion: ability to limit maximum file transfer

### ISSUE THREAD

**Issue by arlandi1974** [pydio/pydio-sync#138]
hi!

if you can add ability to set a limit for maximum file transfer at one time. i'm using pydio to upload to my hosting account with unlimited storage, but it will very often hit 100% for I/O usage. limiting the simultaneous transfer to just 1 or 2 transfers at one time may reduce that limit. 

i may not be the only pydio user with this scenario.

**Comment by 7omate** [comment]
If you want to experiment with this setting you can add `"poolsize": 2` (or 1) in configs.json, this file is located next to `pydio.log` (About > Open Logs).
I don't think this deserves a GUI setting, as tweaking this is a fairly clear sign that your server is undersized compared with the size / number of files you're trying to sync.

**Comment by 7omate** [comment]
There is now a GUI setting for this. Next step would be to have rate limiting in place but that's not yet in the roadmap.
