### ISSUE TITLE
Call to undefined function Doctrine\Common\Cache\apc_fetch()

### ISSUE THREAD

**Issue by deajan** [pydio/pydio-sync#150]
Hello,

The following occured on a fresh Pydio 7.0.1 install (with cache option enabled while install) on CentOS 7 using php70-php-fpm.
Indeed, I don't have apc installed, but there should be tests to avoid this maybe (as the installer states) ?

**Comment by cdujeu** [comment]
hello @deajan not the right repository at all :-)
please post in the pydio/pydio-core instead.
thx
-c

**Comment by deajan** [comment]
Ohh sorry, I didn't realize I was in the sync client repo :)
