### ISSUE TITLE
Error while parsing request result

### ISSUE THREAD

**Issue by Raggazzoo** [pydio/pydio-sync#152]
Hello,

I'm a new user of pydio and I'm impressed by this software!

I only got one issue with podiosync.
When I try to login to my workspace, I got this error :
![sans titre](https://cloud.githubusercontent.com/assets/1357727/20094583/38601572-a5a2-11e6-90f1-7fa19b50f67a.png)

Does someone already got this issue?
Thank's

**Comment by 7omate** [comment]
Try without ws-my-files in the URL

**Comment by Raggazzoo** [comment]
I already tried without ws-my-files and I got the same issue.

**Comment by Raggazzoo** [comment]
It seems to be an apache configuration error.

There is my pydio-le-ssl.conf
![sans titre](https://cloud.githubusercontent.com/assets/1357727/20139821/55bee530-a688-11e6-996d-a0b92e951eae.png)

**Comment by Raggazzoo** [comment]
I'm on pydio 7.0.1 by the way

**Comment by 7omate** [comment]
Did you have a look at the .htaccess file?
I think you need to tweak something if you want to use a sudomain

**Comment by Raggazzoo** [comment]
I take the pydio VAPP ovf template and now I got this
![image](https://cloud.githubusercontent.com/assets/1357727/20169784/b2741cea-a729-11e6-95f4-5c61f6ce4596.png)
![image](https://cloud.githubusercontent.com/assets/1357727/20169799/be9d3876-a729-11e6-92b5-4d5480355382.png)

I tried somethings to setup the subdomain but with no result...

**Comment by 7omate** [comment]
Hi, did you read https://pydio.com/en/docs/v7/checking-sync and tried https://yourserver.tld/runTests.php?api=true (sample workspace slug: my-files)?

Do you understand what you're doing ? The above htaccess looks like a 6.4.x htaccess and shouldn't work with 7.0.1. That's a current one https://github.com/pydio/pydio-core/blob/develop/core/src/.htaccess

**Comment by Raggazzoo** [comment]
I found the error, letsencrypt modify th Virtualhost in auto mode and corrupts everything.
I made my certificate manually and now it's OK!

I'm on 6.0.8 because I use the PydioVAPP 1.1.
I will update it step by step to 6.4 and maybe to 7.0.1.

Thank's for your time =)

**Comment by 7omate** [comment]
Happy you solved the problem!
