### ISSUE TITLE
Sync large files between PydioSync and the Core server

### ISSUE THREAD

**Issue by Raggazzoo** [pydio/pydio-sync#153]
Hello,

I use Pydio 7.0.1 with PydioSync 1.2.8 build 529b363b282f4198d7cf1b70277474c80895fa7b.

Everything is OK, the structure directory and a big part of my files are syncing except file larger than 50Mb.
![image](https://cloud.githubusercontent.com/assets/1357727/20275498/12b6d3e6-aa99-11e6-9431-7ae7a11899c0.png)
When using the web upload it works.
![image](https://cloud.githubusercontent.com/assets/1357727/20275885/71778e7e-aa9a-11e6-8041-1d5d44c1da96.png)
![image](https://cloud.githubusercontent.com/assets/1357727/20276099/2a325bce-aa9b-11e6-9258-a95b61d92ed9.png)

Someone got an idea?
Thank's

**Comment by 7omate** [comment]
From the picture it looks like the file **pc78.pdf** is still uploading...
Did you have a look at the server logs? (Search for ERROR)

Also try to check PydioSync logs (%AppData%/Pydio/pydio.log)

**Comment by Raggazzoo** [comment]
Hello again =)

On server log I got nothing except
![image](https://cloud.githubusercontent.com/assets/1357727/20301434/8e332a6c-ab23-11e6-8954-673cdab97a68.png)
ajxp_acces.log
![image](https://cloud.githubusercontent.com/assets/1357727/20301454/a353d086-ab23-11e6-859a-edcc16937093.png)


In PodioSync log I found this
`File "C:\BuildAgent\work\a00136d723583ad3\build\pydio-agent\out01-PYZ.pyz\pydio.job.localdb", line 754, in on_deleted
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 10340 and this is thread id 11928`

On this screenshot you can see on the left the file wich not sync with the server, it was copy in the PodioSync folder. And on the right th file uploaded by the web interface wich is sync with the agent.
![image](https://cloud.githubusercontent.com/assets/1357727/20301322/1c66adbe-ab23-11e6-8767-05f254f85b8d.png)

I have an other file of 40Mb on root folder of PydioSync/myFiles with the same problem.

Thank's =)

**Comment by 7omate** [comment]
Uhm... Strange PydioSync Error... 

Did you try a resync? 
Stop/Start PydioSync?

**Comment by Raggazzoo** [comment]
Yes I even tried on an other PC and restart server.

For information both of my PC are Windows 10 pro 64.

**Comment by 7omate** [comment]
When you say "PydioSync 1.2.8 build 529b363" you mean PydioSync available at https://pydio.com/en/products/downloads/pydiosync-desktop-app correct?

Do you get the PydioSync ERROR everytime you relaunch it? You may need to
- Stop PydioSync (make sure no pydio process is running)
- manually remove the .sqlite files in %AppData%/Pydio/sync_id 
- Start PydioSync again

**Comment by Raggazzoo** [comment]
Yes the 64 bits installer.

Do I have to remove the file "sequences" too?

**Comment by 7omate** [comment]
yes

**Comment by Raggazzoo** [comment]
After relaunch the agent, the file seems to be correctly created.
![image](https://cloud.githubusercontent.com/assets/1357727/20308504/7f89592a-ab44-11e6-9c37-006337df9dae.png)

The agent find something like 930 changes and stop with the status "Synchronized"
![image](https://cloud.githubusercontent.com/assets/1357727/20308387/f059039a-ab43-11e6-9ed3-7ef139b54bfc.png)

And it still the same, the big file waiting to sync but I got ne network activity
![image](https://cloud.githubusercontent.com/assets/1357727/20308491/6f444962-ab44-11e6-98cb-1add6f936e75.png)

**Comment by 7omate** [comment]
Can you try a RESYNC now and check pydio.log?

**Comment by Raggazzoo** [comment]
Okay I clicked here
![image](https://cloud.githubusercontent.com/assets/1357727/20309057/ca9a3496-ab46-11e6-8da6-900e81387f17.png)
It resyncs everything, detects local changes and still stop on synchronized.

I have add a TEST.txt file and it syncs immediately...

**Comment by 7omate** [comment]
There are no ERRORS concerning the upload of **pc78.pdf** ?
Can you try to rename it ? `pc78-synctest.pdf`

**Comment by Raggazzoo** [comment]
No, there is the log file [pydio.log.txt](https://github.com/pydio/pydio-sync/files/592238/pydio.log.txt)

Do you want to rename it from podyosync or web interface?

**Comment by 7omate** [comment]
Windows Explorer since as far as I understood, the Upload was failing.

**Comment by Raggazzoo** [comment]
Rename it doesn't change anything...

**Comment by 7omate** [comment]
Meaning no local change is detected? Can you create and (after sync) delete a text.txt file ?

**Comment by Raggazzoo** [comment]
No no change with this file, the pc78.pdf.
My TEST.txt is syncing from PydioSync, I add and delete it without any problem.

That's why I think this is a filesize problem.

**Comment by Raggazzoo** [comment]
I have tried everything and I really don't understand why it doesn't want sync files over 40Mb...

There is the specs of my VM : 2 vCPU, 2 Gb of RAM, 100Gb of disk with ubuntu 16.04.1 LTS.

**Comment by Raggazzoo** [comment]
Is it possible to get paid support package for community edition?

**Comment by 7omate** [comment]
Yes it should be possible.
Use this form:
https://pydio.com/contact

You can address your message to David, saying you have sync issues with large files and Thomas needs to look into your problem, possibly with team viewer or similar.

**Comment by Raggazzoo** [comment]
Ok thank's!
