### ISSUE TITLE
Creating file over WebDav causes PydioSync to sync at 0KB

### ISSUE THREAD

**Issue by phiyuku** [pydio/pydio-sync#156]
When you create a file over WebDav, PydioSync syncs it at 0KB. It looks like it just creates the file locally rather than grab it from the server based on the logs. If you do make an edit a type of "content" will be added to ajxp_changes and this will update the file fully.

ajxp_changes shows no difference between a create from WebDav and a create by uploading on Pydio WebUI so I am unsure why this is happening.

2017-01-08 00:27:04 INFO    1604  Thread-1 logging : 1627 | info | Processing 1 changes
2017-01-08 00:27:04 INFO    1604  Thread-1 logging : 1627 | info | To be processed 1
2017-01-08 00:27:04 INFO    11328 Thread-138 logging : 1627 | info | /InstantUpload/log.txt <============ MKFILE
2017-01-08 00:27:04 INFO    11328 Thread-138 logging : 1627 | info | New file created at /InstantUpload/log.txt
2017-01-08 00:27:04 INFO    1604  Thread-1 logging : 1627 | info | Checking history for failed changes and retry.

**Comment by 7omate** [comment]
Hi,
MKFILE denotes the creation of an Empty file, if the file is no longer empty a content event should happen and cause the download of the file, if the file was modified the checksum would differ and the file redownloaded.

How do you put content in the files? (There is a bug in the txt editor that comes with Pydio web interface, the firts save doesn't trigger a content modified event)

**Comment by phiyuku** [comment]
The content is part of the create originally. For example I used windows webdav or another webdav client to upload a file. ajxp_changes logs a CREATE but no CONTENT afterwards because it was created with the content. Weirdly enough the online text editor is the one I used to edit and it did add content to ajxp_changes. I have yet to test with a notepad over Windows WebDav.

**Comment by 7omate** [comment]
Ok, so the summary of your intensive testing could be that webdav events occur too early ? They need to happen after the files are complete?

**Comment by cdujeu** [comment]
See #1318, should be closed
