### ISSUE TITLE
Keyring gui not working in (k)Ubuntu 16.10

### ISSUE THREAD

**Issue by MrMEEE** [pydio/pydio-sync#159]
Hi

Thanks for a fantastic product...

I'm having a problem with the Linux Sync.. 

When starting pydio-ui, it request access to a keyring, but the request happens command line:

        XDG_SESSION_ID: 3
        XDG_SESSION_PATH: /org/freedesktop/DisplayManager/Session1
        XDG_SESSION_TYPE: x11
        XDG_VTNR: 7
        _: /home/mj/bin/pydio-ui
DEBUG:root:sys.platform: linux2
DEBUG:root:pydio_module: /home/mj/.local/share/python_keyring
INFO:root:Linux CONFIG DIR EXPANDED: /home/mj/.local/share
INFO:root:Linux DEFAULT_DATA_PATH: /home/mj/.local/share/Pydio
15:44:14 INFO    140078845931136 MainThread Product Version Number 1.2.7 and Version Date July 27 2016
15:44:14 INFO    140078845931136 MainThread -----------------------------------------------
15:44:14 INFO    140078845931136 MainThread Starting agent locally on http://localhost:58387/
15:44:14 INFO    140078845931136 MainThread ------------------------------------------------
15:44:15 INFO    140078845931136 MainThread Structure and Integrity of SQLite file /home/mj/.local/share/Pydio/mrmeee.dk-my-files/pydio.sqlite is intact 
15:44:15 INFO    140078845931136 MainThread Structure and Integrity of SQLite file /home/mj/.local/share/Pydio/mrmeee.dk-my-files/history.sqlite is intact 
15:44:15 INFO    140078845931136 MainThread Structure and Integrity of SQLite file /home/mj/.local/share/Pydio/mrmeee.dk-my-files/changes.sqlite is intact 
**Please enter password for encrypted keyring:** SETTING ICON busy
  -- HTTPMANAGER --   :     "Providing authentication with name QiwcoJJkzvXEV1nh"
  -- HTTPMANAGER --   :     "-----------------------CONNECTION MADE-----------------------"
  -- JOBSMANAGER --   :     "SHOULD UPDATE : mrmeee.dk-my-files"

It work if I provide the password in the cli, but after some time (after suspend) it times out.. and if I start the program without a terminal, then I'm not prompted for the password and the application hangs...

Any ideas????

I'm running KDE..

**Comment by MrMEEE** [comment]
moved to pydio-sync-ui

**Comment by 7omate** [comment]
Hi, this belongs to pydio-agent, pydio-agent accesses the keyring not pydio-ui.

One work around I think would be to put "password": "YOURPASSWORD" in `/home/mj/.local/share/Pydio/configs.json`

You could try using another keyring, or unlocking it when you log in.

**Comment by MrMEEE** [comment]
Hi.. Doesn't work.. I still get prompted for the keyring.. :(

**Comment by 7omate** [comment]
Do you know what keyring you're using ? Is it KDEWallet ?

**Comment by 7omate** [comment]
There should be an option like "automatically unlock keyring whenever I'm logged in"

**Comment by MrMEEE** [comment]
I actually think that this is basically an Ubuntu issue, neigther kdewallet, nor the gnome-wallet-thingy is working with the python keyring in Ubuntu (have only tested 16.10).. I have created the following bug:

https://answers.launchpad.net/ubuntu/+question/447957

Right now I have created the following startup script:

#!/usr/bin/expect
eval spawn pydio-ui
expect "encrypted keyring:"
send "<INSERT DUMMY PASSWORD>\r";
interact

and set the password on the command line...

Maybe there should be added an option in Pydio, to disable the python-keyring integration....

**Comment by fotis400** [comment]
I face the exact same issue in Fedora 27.

I want to run pydio-agent by a script at startup, but it is not possible due to this.
