### ISSUE TITLE
Issue with self signed certificate

### ISSUE THREAD

**Issue by deajan** [pydio/pydio-sync#160]
Hello,

When connecting pydio-sync to my pydio 7.0.3 (works flawlessly in http), this is what I get when using https with a self signed certifcate (trust all SSL certificates checked), I get:

> Server not found (404), is it up and has it Pydio installed ?

I can connect to https://mypydio.mydomain.tld without problems (except for the ssl warning of course).

httpd 2.4.18 used, tried to enable old SSL ciphers, without success.

Nothing reported in client's pydio.log.
Anything I can check ?

Regards,
Ozy.

**Comment by 7omate** [comment]
On which platform is pydio-sync running ? (Windows, Mac, Linux?)

If you're using MacOS... https://pydio.com/forum/f/topic/pydiosync-for-mac-error-while-trying-to-connect-to-cannot-resolve-domain/

**Comment by deajan** [comment]
Running v1.2.9 on Win10 x64

**Comment by 7omate** [comment]
Hi, did you read https://pydio.com/en/docs/v7/checking-sync and tried https://yourserver.tld/runTests.php?api=true (sample workspace slug: my-files)?

**Comment by deajan** [comment]
As told earlier, my setup works great without https so I doubt it's a setup error.
For the sake of sanity I did try runTests.php and well, it works on http.
On https, output is:

> Getting authentication token with user credentials
> 
> Data returned is not JSON! There is something wrong with the API. Exiting.NULL

**Comment by 7omate** [comment]
Thank you for your Cartesian doubt.

This looks like a configuration problem, make sure the rewrite rules are configured in the same way for HTTP and HTTPS.

**Comment by deajan** [comment]
> Thank you for your Cartesian doubt.
Lol

Seems you're right. On my setup I've moved all the .htaccess stuff to main apache config file in order to avoid using ```AllowOverride All``` and exclude some attack surface.
There was a missing rewrite in the https virtualhost part.

Thanks for the help.

**Comment by 7omate** [comment]
Glad it's working :)
