### ISSUE TITLE
checking sync webpage not found

### ISSUE THREAD

**Issue by migueldvb** [pydio/pydio-sync#161]
Trying to open the website linked in the README (https://pydio.com/en/docs/v6/checking-sync) gives the error

```
The requested page "/en/docs/v6/checking-sync" could not be found.
```

**Comment by lthibault** [comment]
@migueldvb Thanks for the heads-up.  Version 6 is at end-of-life, so the correct link is now https://pydio.com/en/docs/v8/checking-sync.

I'll update the readme :)
