### ISSUE TITLE
Cannot log to an HTTPS server

### ISSUE THREAD

**Issue by christianromeni** [pydio/pydio-sync#33]
Hi, i have an Internal Server Error when starting the Client and trying to Log in.

Server Setup:
Gentoo (current)
Apache/2.2.24 (Unix)
Pydio updated from 5.2.3 to 5.3.1 (cleared cache)

Client SetUp
Windows 8.1 Update x64 (latest version)
All Files in C:\Program Files (x86)\PydioSync
Started strat-script.bat (tried both with and without running as admin)
Added all .exe Files to the firewall, allowing all.

![syncerror](https://cloud.githubusercontent.com/assets/1358040/3405443/79c9f962-fd7d-11e3-9965-b54ee633e2c3.png)

Greets - Chris

**Comment by hitchhiker** [comment]
Same with wildcard StartSSL Cert (can't login)

**Comment by corwinou** [comment]
FYI, my Pydio server (v6) is working fine with a wildcard StartSSL cert (personal class2) together with pydiosync on win 7 x64...

**Comment by hitchhiker** [comment]
Mine is a wildcard / multiname cert from StartSSL, win8.1 unable to connect to pydio 6 on win 2012

**Comment by cdujeu** [comment]
@hitchhiker so it's another issue? Did you post somewhere (in the forum?)
Others, can we close this bug now (and maybe reopen more specific sub-issues)?

**Comment by hitchhiker** [comment]
I've moved to another platform, I couldn't resolve that issue. I can't speak to whether it should be closed or not :( sorry.

**Comment by cdujeu** [comment]
ok too bad, you were quick :-)
Closing until someone reopens.
