### ISSUE TITLE
Mac sync client - nginx pydio server - not working

### ISSUE THREAD

**Issue by DocEmmetBrown** [pydio/pydio-sync#46]
Hi Charles,

I can't manage to get pydio-sync working on my mac.
client setup : 
Mac OS X Mavericks (last updates OK)
Server setup : 
Debian wheezy up to date
nginx & php5-fpm
fresh install from tarball pydio 5.3.2
https vhost only with self-signed certificate

when I try to connect, 
I got this red panel telling me : 
Error while trying to connect to https://pydio.mydomain.com (Internal Server Error): 
Did you enter the correct login/password?
If you are using https, is your certificate self-signed? If yes, check "Trust SSL certificate"

In the nginx log I can see only this line : 
<my_ip> - <my_user> [23/Aug/2014:14:11:44 +0200] "GET /api/pydio/state/user/repositories?format=json HTTP/1.1" 200 78 "-" "python-requests/2.2.1 CPython/2.7.2 Darwin/13.3.0"

I'm positively sure that the login / passwd are correct and the SSL checkbox is checked :)

I can provide the log of the pydio-sync-agent if you wish, but I'd rather send it directly to you...

You can contact me If you need/want more details, I'd be glad to help.

Cheers.

**Comment by ccampo** [comment]
just installed pydio mac yosemite client. the ui does not allow me to do settings. Doing http://localhost:5556 in the brower asks for my PydioSyncAuthRealm which I dont know. What can I do ?

**Comment by cdujeu** [comment]
@ccampo can you post some screenshots? What do you mean by "does not allow me to do settings"?
-c

**Comment by ccampo** [comment]
I started the pydio-ui on a Mac Yosemite. I get the icon of Pydio-ui in menu bar. Enabled menu items als About and Exit. Settings is disabled. I started it from the command line and it was trying to access the agent periodically on localhost:5556 so I entered that url in my browser. Get a login dialog but have no idea what the user and password is. My pydio installation is in the internet. Yet I had no change to enter the URL.

**Comment by cdujeu** [comment]
mmm, strange. And you simply installed using the DMG installer, right? Could you have a look inside ~/Library/Application Support/Pydio ( ~ means your user directory, like /Users/yourmacusername) and list the content?
-c

**Comment by ccampo** [comment]
I simply installed from DMG !!. I have a log file which is empty and a config file which contains "pydio:5556:xxxx"  where xxx is some hash or something approx 20 chars

**Comment by cdujeu** [comment]
And the systray (= top right UI) is still not seeing the agent (Settings disabled)?

**Comment by ccampo** [comment]
just installed it again. I have two processes running pydio-agent, one process is pydio-ui. empty log and the config as I described.....console says "Please switch away from OnDemand to KeepAlive" for both jobs. Pydio-UI frequently frequently climbs up with CPU usage to 20 % or something....

**Comment by ccampo** [comment]
I started Pydio-UI from the cmd line and does "Server set" "Username set" "Providing authentication " 5 times "Skipping authentication" "Max Connection attempts reached" "update ports from config" and then it starts again......

**Comment by ccampo** [comment]
so I took the authentication info from the ports.config (username:password I guess) and entered it in the browser into the login dialog and it was rejected. So maybe that is the problem that the user, passwort info in the ports.config is invalid or not accepted by the agent and the ui gets into a loop

**Comment by cdujeu** [comment]
Indeed, maybe it's the problem. Is keypair is regenerated and different on each agent start. 
Except if you manually pass the --api_user --api_password when starting the agent, and you should be able to use that to access the UI.
-c

**Comment by yavama** [comment]
Hi, i have this too ! what username and password its about ?
![screenshot from 2016-02-25 19 54 58](https://cloud.githubusercontent.com/assets/17200559/13330638/fa19bf38-dbf9-11e5-8222-c883a70ebea5.png)
