### ISSUE TITLE
PC / Mac sync not functioning well

### ISSUE THREAD

**Issue by lovellstudios** [pydio/pydio-sync#59]
PC sync does not work - it's possible that we're not installing/running it correctly - but the new version just stalls (I don't remember if there was any errors.)

We have the Mac version on two computers tied to the one username account and on one machine it has an error saying Conflicts detected, cannot continue. There's no option to open pydio or stop sync - I've ran the script several times but comes up the same with the conflicts detected error.

The other Mac seemed to be syncing last I checked - but we're not trusting it fully yet.

**Comment by cdujeu** [comment]
closing until there is some news

**Comment by antoine64** [comment]
Same problem here with the same error : 
```
14:39:56 ERROR   4529176576 Thread-1 Unexpected Error: [sdk operation] [bulk_stat] /Icon (Encoding problem, failed emptying bulk_stat, exiting to avoid infinite loop)
Traceback (most recent call last):
  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.job.continous_merger", line 406, in run
  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.job.change_stores", line 254, in detect_unnecessary_changes
  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.job.change_stores", line 279, in filter_w_stat
  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.sdk.remote", line 488, in bulk_stat
PydioSdkException: [sdk operation] [bulk_stat] /Icon (Encoding problem, failed emptying bulk_stat, exiting to avoid infinite loop)
```

**Comment by cdujeu** [comment]
Hi Antoine, thx for reporting. 
Can you provide more info
> What's your server OS ? What's your server encoding? (try echo $LANG on the command line)
> Client encoding?

**Comment by antoine64** [comment]
Server is Debian 7 with Nginx & php-fpm 5.6
Server encoding is fr_FR.UTF-8
Client encoding is the same fr_FR.UTF-8

**Comment by cdujeu** [comment]
Did the error appear as soon as you started syncing ?

**Comment by antoine64** [comment]
I started syncing with another version of Pydio Sync (0.8.10 release). Error appears with the current develop package version.

**Comment by IdealisMedias** [comment]
Hello,
I also have the same problem as Antoine 64 with the same configuration (Debian 7 and encoding fr_FR.UTF8). I'm on Mac os X Yosemite with Pydio Sync 0.8.10.
I can upload files with accents éèà in both directions, but when the folder is too large it gives me the error:
PydioSdkException: [sdk operation] [bulk_stat] /Soci\xe9t\xe9 Id\xe9alis M\xe9dias/Embauche/Community Manager/Alyanakian D\xe9borah (Encoding problem, failed emptying bulk_stat, exiting to avoid infinite loop).
Now pydio sync does not want to connect to the server.
Thank you.
