### ISSUE TITLE
Automatic sync doesn't work OS X - Yosemite 

### ISSUE THREAD

**Issue by skerbis** [pydio/pydio-sync#73]
I've configured Sync Frequency "upload only", Automatic Sync and "Always prefer local version". Manual Sync works fine. - German Version of OS X.

**Comment by skerbis** [comment]
Sorry. I will test it again tomorrow

**Comment by cdujeu** [comment]
@skerbis ?

**Comment by skerbis** [comment]
Hey tried the fresh version today, seems that it works fine now.
