### ISSUE TITLE
Disable sync from workspace does not work

### ISSUE THREAD

**Issue by goranvanderlaarse** [pydio/pydio-sync#84]
After setting ‘syncable workspace’ to ‘no’, it still let's users sync that workspace. I don get any errors and my settings are saved. 

Removing the “Syncable” feature from the workspace also makes no difference.

As an admin it seems one cannot disable the sync feature.

**Comment by cdujeu** [comment]
ok it's a server-side issue!

**Comment by cdujeu** [comment]
Should be fixed now
