### ISSUE TITLE
Linux agent using wrong APP_DATA_DIR

### ISSUE THREAD

**Issue by cdujeu** [pydio/pydio-sync#85]
Seems like sometimes the agent uses .config/pydio instead of .local/share/Pydio

**Comment by Flauschbaellchen** [comment]
After starting the agent, `~/.config/pydio` isn't used and `~/.local/share/Pydio` isn't created.
Any ENV variables you'd like me to provide?

**Comment by cdujeu** [comment]
Fixed, seems like appdirs module is messing things up in some cases.

**Comment by Flauschbaellchen** [comment]
I can confirm that the fix is working.
```
  -- HTTPMANAGER --   :     "Server set to http://127.0.0.1:5556"
  -- HTTPMANAGER --   :     "Username set to f6IbfXVqSuC9QlI2"
```
Thanks again.
