### ISSUE TITLE
Wrong path output while starting pydio-ui

### ISSUE THREAD

**Issue by Flauschbaellchen** [pydio/pydio-sync#86]
Don’t know if this kind of related to #85 or relevant at all:
After starting the UI, the first line looks like a debug output:
(within `/data/downloads/PydioSync-Linux`):
```
[11:48:02] % ./pydio-ui/pydio-ui
“/data/downloads/PydioSync-Linux/pydio-agent.exe”
Trying to start agent
— HTTPMANAGER — : “Server set to http://127.0.0.1:5556”
— HTTPMANAGER — : “Username set to ”
[…]
```

As this is Linux, an “exe”-file does not exist.
Additionally, the path is always generated by taken the current location of the caller, not the location of the executable as the base path.
Thus calling with absolute path from within `/` gives `"//pydio-agent.exe"`
Afaik, getting the path by `../agent/pydio-agent` from the current running script (`pydio-ui`) would be more correct.

**Comment by cdujeu** [comment]
should be fixed in latest (renamed agent/ to pydio-agent/ btw)

**Comment by Flauschbaellchen** [comment]
Hi charles,
thanks for the fix. It's working now and the agent is started automatically:
`"Should try to start agent at /data/downloads/PydioSync-Linux/pydio-ui/../pydio-agent/pydio-agent"`
