### ISSUE TITLE
pydio-ui doesn't recognize SIGINT and SIGTERM

### ISSUE THREAD

**Issue by Flauschbaellchen** [pydio/pydio-sync#87]
When receiving an interrupt (SIGINT) or shutdown signal (SIGTERM) the pydio-ui does stop, but don't cleanup the pydio-agent.
it only terminates gracefully when exiting the pydio-ui by clicking on the X- or "Exit"-button.

If started again, it starts up a new pydio-agent process which results in multiple processes doing the same thing and polluting the system.

To fix this, either cleanup the pydio-agent on exit - or check if the agent is already running on startup.
I would prefer the first solution, because if an user kills/interrupts/exits the pydio-ui there is no reason the run the agent in the background further on.
Moreover, if the user does this kind of thing, he assumes that every sync is shut down and nothing is running anymore.

Edit: Running latest dev-package on Linux :)

**Comment by cdujeu** [comment]
I think that until we don't make a proper packaging and associated linux services, you should use the parameter to start ui and NOT start agent at the same time. You can use -skipAgentStart (or -- not sure) on the ui binary.
-c
