### ISSUE TITLE
Server Name Indication support

### ISSUE THREAD

**Issue by babs** [pydio/pydio-sync#94]
It seems that, it doesn't support SNI.
When I try on my server, it gives me the default cert (and an error :) ) but using a standard browser, it works.

D.

**Comment by 7omate** [comment]
What's the status on for this ?
What your client platform?
Is your cert valid?
Can you send me a private message with test credentials on our forum https://pydio.com/forum/members/7omate/

**Comment by babs** [comment]
Unfortunately, I have no more pydio running  :/
