### ISSUE TITLE
[osx] File is not correct after download

### ISSUE THREAD

**Issue by erixtekila** [pydio/pydio-sync#95]
I get lots of error in the osx pydiosync.
PydioSync v1.0.0 - Build fcb966783adec1b2f76d0b93233710ca51a009b4 
I try to sync a new local folder from an existing repository.

Here is the exception 

```
2015-05-12 18:27:16 ERROR   4455305216 Thread-1 logging:1596 | error | 
Traceback (most recent call last):
  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.job.continous_merger", line 492, in processor_callback
  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.job.change_processor", line 83, in process_change
  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.job.change_processor", line 265, in process_local_mkfile
  File "/Users/charles/Desktop/TeamCity/buildAgent/work/a00136d723583ad3/build/pydio-agent/out01-PYZ.pyz/pydio.sdk.local", line 57, in mkfile
IOError: [Errno 2] No such file or directory: u'/Users/m34/Pydio/Taf2/02_bootstrap/supports/_book/fr/gitbook/plugins/gitbook-plugin-anchors/plugin.js~'
2015-05-12 18:30:47 ERROR   4455305216 Thread-1 logging:1596 | error | [sdk operation] [download] /marionette/00-deroule.txt (File is not correct after download)
```

**Comment by cdujeu** [comment]
Did you disable output_buffering on your server?
-c

**Comment by erixtekila** [comment]
In the diagnostic panel, I get the messge : "PHP Output Buffer disabled" "No".
BTW, how is it possible to set output_buffering for nginx ?

**Comment by erixtekila** [comment]
Here is my config.

<table id="selectable_div-1" class="selectable_div sort-table" cellspacing="0" width="100%"><tbody><tr class="ajxpNodeProvider ajxpNodeLeaf" id="item-diagnosticclient"><td><span style="cursor: default; display: block; position: relative; z-index: 900;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">Client</span></span></td><td><span class="text_label">Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0</span></td></tr><tr class="even ajxpNodeProvider ajxpNodeLeaf" id="item-diagnosticcommand-line-available"><td><span style="cursor: default; display: block; position: relative;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">Command Line Available</span></span></td><td><span class="text_label">Yes</span></td></tr><tr class="ajxpNodeProvider ajxpNodeLeaf" id="item-diagnosticdom-enabled"><td><span style="cursor: default; display: block; position: relative;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">DOM Enabled</span></span></td><td><span class="text_label">Yes</span></td></tr><tr class="even ajxpNodeProvider ajxpNodeLeaf" id="item-diagnosticexif-enabled"><td><span style="cursor: default; display: block; position: relative;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">Exif Enabled</span></span></td><td><span class="text_label">Yes</span></td></tr><tr class="ajxpNodeProvider ajxpNodeLeaf selected selected-focus" id="item-diagnosticgd-enabled"><td><span style="cursor: default; display: block; position: relative;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">GD Enabled</span></span></td><td><span class="text_label">Yes</span></td></tr><tr class="even ajxpNodeProvider ajxpNodeLeaf" id="item-diagnosticupload-max-size"><td><span style="cursor: default; display: block; position: relative;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">Upload Max Size</span></span></td><td><span class="text_label">20G</span></td></tr><tr class="ajxpNodeProvider ajxpNodeLeaf" id="item-diagnosticmemory-limit"><td><span style="cursor: default; display: block; position: relative;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">Memory Limit</span></span></td><td><span class="text_label">128M</span></td></tr><tr class="even ajxpNodeProvider ajxpNodeLeaf" id="item-diagnosticmax-execution-time"><td><span style="cursor: default; display: block; position: relative;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">Max execution time</span></span></td><td><span class="text_label">30</span></td></tr><tr class="ajxpNodeProvider ajxpNodeLeaf" id="item-diagnosticsafe-mode"><td><span style="cursor: default; display: block; position: relative;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">Safe Mode</span></span></td><td><span class="text_label">0</span></td></tr><tr class="even ajxpNodeProvider ajxpNodeLeaf" id="item-diagnosticsafe-mode-gid"><td><span style="cursor: default; display: block; position: relative;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">Safe Mode GID</span></span></td><td><span class="text_label">0</span></td></tr><tr class="ajxpNodeProvider ajxpNodeLeaf" id="item-diagnosticxml-parser-enabled"><td><span style="cursor: default; display: block; position: relative;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">Xml parser enabled</span></span></td><td><span class="text_label">1</span></td></tr><tr class="even ajxpNodeProvider ajxpNodeLeaf" id="item-diagnosticmcrypt-enabled"><td><span style="cursor: default; display: block; position: relative;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">MCrypt Enabled</span></span></td><td><span class="text_label">Yes</span></td></tr><tr class="ajxpNodeProvider ajxpNodeLeaf" id="item-diagnosticserver-os"><td><span style="cursor: default; display: block; position: relative;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">Server OS</span></span></td><td><span class="text_label">Linux</span></td></tr><tr class="even ajxpNodeProvider ajxpNodeLeaf" id="item-diagnosticsession-save-path"><td><span style="cursor: default; display: block; position: relative;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">Session Save Path</span></span></td><td><span class="text_label">/var/lib/php5/sessions</span></td></tr><tr class="ajxpNodeProvider ajxpNodeLeaf" id="item-diagnosticsession-save-path-writeable"><td><span style="cursor: default; display: block; position: relative;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">Session Save Path Writeable</span></span></td><td><span class="text_label">1</span></td></tr><tr class="even ajxpNodeProvider ajxpNodeLeaf" id="item-diagnosticphp-version"><td><span style="cursor: default; display: block; position: relative;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">PHP Version</span></span></td><td><span class="text_label">5.5.21-1+deb.sury.org~precise+2</span></td></tr><tr class="ajxpNodeProvider ajxpNodeLeaf" id="item-diagnosticlocale"><td><span style="cursor: default; display: block; position: relative;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">Locale</span></span></td><td><span class="text_label">fr_FR.UTF-8</span></td></tr><tr class="even ajxpNodeProvider ajxpNodeLeaf" id="item-diagnosticdirectory-separator"><td><span style="cursor: default; display: block; position: relative;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">Directory Separator</span></span></td><td><span class="text_label">/</span></td></tr><tr class="ajxpNodeProvider ajxpNodeLeaf" id="item-diagnosticphp-apc-extension-loaded"><td><span style="cursor: default; display: block; position: relative;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">PHP APC extension loaded</span></span></td><td><span class="text_label">Yes</span></td></tr><tr class="even ajxpNodeProvider ajxpNodeLeaf" id="item-diagnosticphp-output-buffer-disabled"><td><span style="cursor: default; display: block; position: relative;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">PHP Output Buffer disabled</span></span></td><td><span class="text_label">No</span></td></tr><tr class="ajxpNodeProvider ajxpNodeLeaf" id="item-diagnosticmagic-quotes-disabled"><td><span style="cursor: default; display: block; position: relative;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">Magic quotes disabled</span></span></td><td><span class="text_label">Yes</span></td></tr><tr class="even ajxpNodeProvider ajxpNodeLeaf" id="item-diagnosticupload-tmp-dir-writeable"><td><span style="cursor: default; display: block; position: relative;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">Upload Tmp Dir Writeable</span></span></td><td><span class="text_label">1</span></td></tr><tr class="ajxpNodeProvider ajxpNodeLeaf" id="item-diagnosticphp-upload-max-size"><td><span style="cursor: default; display: block; position: relative;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">PHP Upload Max Size</span></span></td><td><span class="text_label">21474836480</span></td></tr><tr class="even ajxpNodeProvider ajxpNodeLeaf" id="item-diagnosticphp-post-max-size"><td><span style="cursor: default; display: block; position: relative;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">PHP Post Max Size</span></span></td><td><span class="text_label">21474836480</span></td></tr><tr class="ajxpNodeProvider ajxpNodeLeaf" id="item-diagnosticusers-enabled"><td><span style="cursor: default; display: block; position: relative;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">Users enabled</span></span></td><td><span class="text_label">1</span></td></tr><tr class="even ajxpNodeProvider ajxpNodeLeaf" id="item-diagnosticguest-enabled"><td><span style="cursor: default; display: block; position: relative;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">Guest enabled</span></span></td><td><span class="text_label"></span></td></tr><tr class="ajxpNodeProvider ajxpNodeLeaf" id="item-diagnosticwriteable-folders"><td><span style="cursor: default; display: block; position: relative;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">Writeable Folders</span></span></td><td><span class="text_label">[<b>cache</b>:true,<br> <b>data</b>:true]</span></td></tr><tr class="even ajxpNodeProvider ajxpNodeLeaf" id="item-diagnosticzlib-enabled"><td><span style="cursor: default; display: block; position: relative;" class="list_selectable_span ajxp_draggable protomenu_selector"><span style="padding-left: 24px; background-repeat: no-repeat; background-position: 5px 4px; background-image: url(&quot;plugins/gui.ajax/res/themes/orbit/images/mimes/16/susehelpcenter.png&quot;);" class="text_label" id="ajxp_label">Zlib Enabled</span></span></td><td><span class="text_label">Yes</span></td></tr></tbody></table>

**Comment by erixtekila** [comment]
Anyway, give a hint : is output_buffering a performance bottleneck ?
In several chapters of the docs, you state to turn it off : 
- https://pyd.io/docs/v6/workspaces/additional-features/watches-and-notifications/ 
- https://pyd.io/docs/v6/enriching-your-users-experience/tuning-server-performances/

Please, what is the best setting in order to use messa?

**Comment by erixtekila** [comment]
OK, I get it, at last.

One needs to disable php output buffering, otherwise, pydiosync won't work at all.
One should also be warned that php.ini could have multiple declarations of it, in multiple place !…

It should be stated more clearly in the docs IMHO, because it's the default settings.

You could close this issue.

**Comment by cdujeu** [comment]
Eric, the "Output Buffering" warning is the VERY FIRST thing displayed in the diagnostic window when you install Pydio... But well, let's highlight it more everywhere else :-)

**Comment by erixtekila** [comment]
I may have installed an old version ?!
It didn't appeared to me.
